#pragma once
#ifndef __KL_VERSION_H__
#define __KL_VERSION_H__

#define KL_STR(x) #x

#define KL_VERSION_MAJOR 1
#define KL_VERSION_MINOR 0
#define KL_VERSION_PATCH 0

#define KL_VERSION_MAJOR_STR KL_STR(KL_VERSION_MAJOR)
#define KL_VERSION_MINOR_STR KL_STR(KL_VERSION_MINOR)
#define KL_VERSION_PATCH_STR KL_STR(KL_VERSION_PATCH)


#endif
